stages:
  - build
  - test
  - package

build_job:
  stage: build
  tags:
    - windows
  script:
    - mvn clean compile

test_job:
  stage: test
  tags:
    - windows
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

package_job:
  stage: package
  tags:
    - windows
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week